import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'

import Posts from 'components/Posts'
import Comment from 'components/Comment'

import { db } from 'firebase/client'
import { onSnapshot, collection, query, orderBy, doc } from 'firebase/firestore'
import { BsArrowLeft } from 'react-icons/bs'

const SinglePost = () => {
  const [post, setPost] = useState([])
  const [comments, setComments] = useState([])

  const router = useRouter()
  const { id } = router.query

  useEffect(() => onSnapshot(query(collection(db, 'posts', id, 'comments'), orderBy('createdAt', 'desc')),
    snapshot => setComments(snapshot.docs)
  ), [db, id])

  useEffect(() =>
    onSnapshot(doc(db, 'posts', id), snapshot => {
      setPost(snapshot.data())
    }), [db]
  )

  return (
    <>
      <Head>
        <title>{post?.username} on Twitter: "{post?.text}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <section className='sm:ml-[81px] xl:ml-[340px] w-[600px] max-h-screen border-r border-gray-400 text-white py-2'>
        <div className='sticky top-0 bg-black flex items-center gap-4 font-medium text-[20px] px-4 py-2'>
          <BsArrowLeft
            className='cursor-pointer'
            onClick={() => router.push('/')}
          />
          Twitter
        </div>
        <Posts
          id={id}
          post={post}
        />

        <div className='border-t border-gray-700'>
          {comments.length > 0 && (
            <div className='pb-72'>
              {comments.map((comment) => (
                <Comment
                  key={comment.id}
                  id={comment.id}
                  comment={comment.data()}
                />
              ))}
            </div>
          )}
        </div>
      </section>
    </>
  )
}

export default SinglePost
